sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.1.2
  - 2.1
env:
  - "RAILS_VERSION=3.2.22.5"
  - "RAILS_VERSION=4.2.9"
cache:
  bundler: true
install:
  - gem update --system
  - gem install bundler
  - bundle install --jobs=3 --retry=3
branches:
  only:
    - master
